import Image from "next/image"
import Link from "next/link"
import { ArrowDownRight, ArrowRight, Building2, CalendarDays, MapPin, MessageCircle, Search, Send, ShieldCheck } from "lucide-react"
import { opportunities, opportunityTypeLabel } from "@/lib/opportunities"
import { newsItems, participantCompanies, topics } from "@/lib/site-content"
import { HeroMediaCarousel } from "@/components/home/hero-media-carousel"
import { PhotoCredit } from "@/components/photo-credit"

function SectionTitle({ index, eyebrow, title, light = false }: { index: string; eyebrow: string; title: React.ReactNode; light?: boolean }) {
  return <div className={`flex items-start gap-4 border-b-2 pb-6 ${light ? "border-white text-white" : "border-foreground"}`}><span className={`font-mono text-sm font-black ${light ? "text-action-yellow" : "text-primary"}`}>{index}</span><div><p className="font-mono text-xs font-black tracking-[0.24em]">{eyebrow}</p><h2 className="mt-3 text-4xl font-black leading-tight tracking-tight sm:text-6xl">{title}</h2></div></div>
}

export function PosterHome() {
  const publicProjects = opportunities.filter((item) => item.type !== "company_participation").slice(0, 3)
  return <>
    <section className="poster-grid relative overflow-hidden border-b-2 border-foreground bg-paper pt-20">
      <div className="mx-auto grid min-h-[760px] max-w-7xl lg:grid-cols-[.97fr_1.03fr]">
        <div className="relative min-h-[520px] overflow-hidden lg:min-h-0">
          <div className="absolute inset-0 bg-primary" />
          <div className="poster-photo-cut absolute inset-5 overflow-hidden border-2 border-foreground bg-white sm:inset-8"><HeroMediaCarousel /></div>
          <div className="absolute right-4 top-5 grid h-36 w-36 rotate-6 place-items-center bg-action-orange text-center font-mono text-4xl font-black leading-none text-white sm:h-44 sm:w-44 sm:text-5xl">次回<br />↗</div>
          <div className="absolute bottom-5 left-4 max-w-[85%] border-2 border-foreground bg-action-yellow p-4 sm:bottom-8 sm:left-8 sm:p-5"><p className="font-mono text-xs font-black">次回イベント</p><p className="mt-1 text-xl font-black sm:text-2xl">第6回 Table Match 福岡</p><p className="mt-2 flex flex-wrap gap-4 text-xs font-bold"><span>2026年10月中旬予定</span><span>福岡市内</span></p></div>
        </div>
        <div className="relative z-10 flex flex-col justify-center border-t-2 border-foreground px-5 py-14 sm:px-8 lg:border-l-2 lg:border-t-0 lg:py-20">
          <p className="font-mono text-sm font-black tracking-[0.16em] text-primary">学生 × 経営者 / 長野・福岡</p>
          <h1 className="mt-6 text-[3.15rem] font-black leading-[.94] tracking-[-.06em] sm:text-[3.8rem] xl:text-[4rem]">同じテーブルから<br /><span className="poster-underline">次の挑戦を。</span></h1>
          <p className="mt-8 max-w-xl text-base font-bold leading-8 sm:text-lg">話して、見つける。つながって、始める。<br />就職も、起業も、まだ名前のない挑戦も。</p>
          <div className="mt-9 grid max-w-xl gap-3 sm:grid-cols-2"><Link href="/projects/table-match-fukuoka-6" className="poster-button poster-button-orange">次回イベントを見る<ArrowRight /></Link><Link href="/about" className="poster-button bg-paper">Table Matchとは<ArrowDownRight /></Link></div>
          <div className="mt-8 flex flex-wrap gap-3 text-xs font-bold"><span className="border-2 border-foreground bg-white px-3 py-2">一人参加OK</span><span className="border-2 border-foreground bg-white px-3 py-2">進路未定OK</span><span className="border-2 border-foreground bg-white px-3 py-2">参加無料</span></div>
        </div>
      </div>
    </section>

    <section aria-label="活動実績" className="border-b-2 border-foreground bg-primary text-white">
      <div className="mx-auto grid max-w-7xl grid-cols-2 md:grid-cols-4">{[["5","過去開催"],["70+","累計参加学生"],["9","累計参加企業"],["LCV","テレビ取材"]].map(([value,label]) => <div key={label} className="border-r-2 border-white/50 px-4 py-8 text-center last:border-r-0 sm:py-11"><p className="font-mono text-4xl font-black sm:text-6xl">{value}</p><p className="mt-2 text-sm font-bold text-white/70">{label}・2026年7月時点</p></div>)}</div>
    </section>

    <section className="border-b-2 border-foreground bg-foreground text-white"><div className="mx-auto grid max-w-7xl lg:grid-cols-[1.35fr_.65fr]"><div className="relative min-h-[360px] overflow-hidden border-b-2 border-white/40 bg-black lg:min-h-[520px] lg:border-b-0 lg:border-r-2"><video autoPlay muted loop playsInline controls preload="metadata" poster="/images/real/students-table.jpg" className="absolute inset-0 h-full w-full object-cover" aria-label="Table Match会場の様子"><source src="/videos/table-match-highlight.mov" type="video/quicktime" /></video><span className="absolute left-4 top-4 bg-action-orange px-3 py-2 font-mono text-xs font-black">Table Match 動画</span><PhotoCredit className="bottom-12" /></div><div className="flex flex-col justify-center p-7 sm:p-10"><p className="font-mono text-xs font-black tracking-[.2em] text-action-yellow">雰囲気</p><h2 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">笑って、食べて、<br />本音で話す。</h2><p className="mt-6 leading-8 text-white/75">説明会のように一方的に聞くのではなく、同じテーブルで互いに質問する。動画から、会場の距離感とあたたかさを感じてください。</p><p className="mt-6 border-l-4 border-action-yellow pl-4 text-sm font-bold">音声なしでも視聴できます。再生できない環境では会場写真を表示します。</p></div></div></section>

    <section id="projects" className="bg-paper px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionTitle index="01" eyebrow="企画" title={<>今、参加できる<br />挑戦を選ぶ。</>} /><div className="mt-10 grid gap-5 lg:grid-cols-3">{publicProjects.map((project) => <article key={project.id} className="group flex flex-col border-2 border-foreground bg-white"><div className="relative aspect-[4/3] overflow-hidden border-b-2 border-foreground"><Image src={project.image} alt="" fill sizes="(max-width: 1024px) 100vw, 33vw" className="object-cover grayscale-[15%] transition duration-500 group-hover:scale-105 group-hover:grayscale-0" /><span className="absolute left-0 top-0 bg-primary px-3 py-2 font-mono text-xs font-black text-white">{opportunityTypeLabel(project.type)}</span><PhotoCredit /></div><div className="flex flex-1 flex-col p-5"><div className="flex items-center justify-between"><span className="bg-action-yellow px-2 py-1 text-xs font-black">{project.status === "open" ? "募集中" : "先行受付"}</span><span className="font-mono text-xs font-bold">{project.price}</span></div><h3 className="mt-5 text-2xl font-black leading-tight">{project.title}</h3><p className="mt-3 flex-1 text-sm leading-7 text-muted-foreground">{project.summary}</p><div className="mt-5 space-y-2 border-t-2 border-foreground pt-4 text-xs font-bold"><p className="flex gap-2"><CalendarDays className="h-4 w-4 text-primary" />{project.date}</p><p className="flex gap-2"><MapPin className="h-4 w-4 text-primary" />{project.location}</p></div><Link href={`/projects/${project.slug}`} className="poster-button mt-5 bg-foreground text-white">詳しく見る<ArrowRight /></Link></div></article>)}</div><div className="mt-8 text-right"><Link href="/projects" className="inline-flex items-center gap-2 border-b-2 border-foreground pb-1 font-black">すべての企画を見る<ArrowRight className="h-5 w-5" /></Link></div></div></section>

    <section id="about" className="border-y-2 border-foreground bg-action-yellow px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionTitle index="02" eyebrow="活動の流れ" title={<>やりたいことは、<br />対話から始まる。</>} /><div className="mt-10 grid border-2 border-foreground bg-paper lg:grid-cols-3">{[
      { n:"01", title:"見つける", text:"多様な価値観に出会い、自分の興味や可能性を広げる。", icon:Search, color:"border-action-orange" },
      { n:"02", title:"聞き合う", text:"経営者や仲間と本音で語り合い、仕事や想いの背景を知る。", icon:MessageCircle, color:"border-action-yellow" },
      { n:"03", title:"動き出す", text:"対話から生まれた気づきを、見学・インターン・挑戦へ。", icon:Send, color:"border-primary" },
    ].map(({n,title,text,icon:Icon,color}) => <article key={n} className={`border-b-2 p-7 last:border-b-0 lg:border-b-0 lg:border-r-2 lg:last:border-r-0 ${color}`}><div className="flex items-start justify-between"><span className="font-mono text-6xl font-black text-primary">{n}</span><Icon className="h-14 w-14" strokeWidth={2.5} /></div><h3 className="mt-8 text-3xl font-black">{title}</h3><p className="mt-4 max-w-sm font-bold leading-8">{text}</p></article>)}</div></div></section>

    <section className="border-b-2 border-foreground bg-action-orange text-white"><div className="mx-auto grid max-w-7xl lg:grid-cols-[270px_1fr]"><div className="border-b-2 border-white p-6 lg:border-b-0 lg:border-r-2 lg:p-10"><p className="font-mono text-5xl font-black leading-[.85] sm:text-6xl">次回<br />イベント</p><p className="mt-5 text-sm font-bold text-white/80">先行受付中</p></div><div className="m-5 grid border-2 border-foreground bg-paper text-foreground sm:m-8 sm:grid-cols-[1fr_auto]"><div className="p-6 sm:p-8"><p className="font-mono text-xs font-black text-primary">イベント / 福岡</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">第6回 Table Match 福岡</h2><div className="mt-5 flex flex-wrap gap-5 text-sm font-bold"><span className="flex gap-2"><CalendarDays className="text-primary" />2026年10月中旬予定</span><span className="flex gap-2"><MapPin className="text-primary" />福岡市内</span></div></div><Link href="/projects/table-match-fukuoka-6" className="grid min-h-32 place-items-center border-t-2 border-foreground bg-action-yellow p-6 font-black sm:w-48 sm:border-l-2 sm:border-t-0">参加を検討する<ArrowRight /></Link></div></div></section>

    <section id="topics" className="bg-primary px-5 py-20 text-white sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionTitle index="03" eyebrow="活動レポート" title={<>人と会社の、<br />その後を知る。</>} light /><div className="mt-10 grid gap-5 lg:grid-cols-3">{topics.map((topic, index) => <Link key={topic.slug} href={`/topics/${topic.slug}`} className="group block border-2 border-white bg-paper text-foreground"><div className="relative aspect-[16/10] overflow-hidden border-b-2 border-foreground"><Image src={topic.image} alt="" fill sizes="(max-width: 1024px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105" /><span className="absolute bottom-0 left-0 bg-action-orange px-3 py-2 font-mono text-xs font-black text-white">{topic.category}</span><PhotoCredit linked={false} /></div><div className="p-5"><p className="font-mono text-xs font-bold text-muted-foreground">{topic.date} / 0{index + 1}</p><h3 className="mt-3 text-xl font-black leading-snug">{topic.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{topic.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 font-black">読む<ArrowRight className="h-4 w-4" /></span></div></Link>)}</div><div className="mt-8 text-right"><Link href="/topics" className="inline-flex items-center gap-2 border-b-2 border-white pb-1 font-black">活動レポート一覧<ArrowRight /></Link></div></div></section>

    <section id="companies" className="border-b-2 border-foreground bg-paper px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionTitle index="04" eyebrow="参加企業" title={<>対話に参加した<br />地域企業。</>} /><p className="mt-6 max-w-2xl text-sm leading-7 text-muted-foreground">過去のTable Match参加企業です。提供済み・公式サイト掲載のロゴデータを使用しています。</p><div className="mt-10 grid grid-cols-2 border-l-2 border-t-2 border-foreground md:grid-cols-3">{participantCompanies.map((company) => <div key={company.name} className={`grid min-h-32 place-items-center overflow-hidden border-b-2 border-r-2 border-foreground p-4 transition hover:bg-action-yellow/20 ${company.surface === "blue" ? "bg-primary" : company.surface === "dark" ? "bg-foreground" : "bg-white"}`}><Image src={company.logo} alt={company.name} width={320} height={120} className={`h-20 w-full object-contain ${company.logoScale === "half" ? "scale-50" : company.logoScale === "large" ? "scale-[1.5]" : ""}`} /></div>)}</div></div></section>

    <section className="border-b-2 border-foreground bg-paper px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.82fr_1.18fr]"><div className="bg-action-orange p-7 text-white sm:p-10"><Building2 className="h-12 w-12" /><p className="mt-8 font-mono text-xs font-black tracking-widest text-action-yellow">企業の方へ</p><h2 className="mt-3 text-4xl font-black leading-tight sm:text-6xl">求人票では、<br />伝わらない魅力を。</h2><p className="mt-6 max-w-lg font-bold leading-8">3時間の対話から、会社見学・インターン・採用・共創へ。学生と企業の間を運営が伴走します。</p><Link href="/for-companies" className="poster-button mt-8 bg-paper text-foreground">企業向け情報を見る<ArrowRight /></Link></div><div className="grid border-2 border-foreground bg-white sm:grid-cols-3">{[["3h","少人数で話せる時間"],["9社","累計参加企業"],["伴走","イベント後の接続支援"]].map(([value,label]) => <div key={label} className="border-b-2 border-foreground p-6 last:border-b-0 sm:border-b-0 sm:border-r-2 sm:last:border-r-0"><p className="font-mono text-5xl font-black text-primary">{value}</p><p className="mt-4 font-black">{label}</p></div>)}<div className="border-t-2 border-foreground p-6 sm:col-span-3"><div className="flex gap-3"><ShieldCheck className="h-6 w-6 shrink-0 text-primary" /><p className="text-sm font-bold leading-7">学生情報の共有は本人の明示同意に基づきます。電話番号・メール・配慮事項は、必要性を確認せず企業へ共有しません。</p></div></div></div></div></section>

    <section id="news" className="bg-white px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionTitle index="05" eyebrow="お知らせ" title="最新のお知らせ。" /><div className="mt-8 border-t-2 border-foreground">{newsItems.map((item) => <Link key={item.slug} href={`/news/${item.slug}`} className="group grid gap-3 border-b-2 border-foreground py-6 hover:bg-action-yellow/15 sm:grid-cols-[140px_110px_1fr_auto] sm:items-center sm:px-4"><time className="font-mono text-sm font-bold">{item.date}</time><span className="font-mono text-xs font-black text-primary">{item.category}</span><span className="text-lg font-black">{item.title}</span><ArrowRight className="transition group-hover:translate-x-2" /></Link>)}</div><div className="mt-8 text-right"><Link href="/news" className="inline-flex items-center gap-2 border-b-2 border-foreground pb-1 font-black">お知らせ一覧<ArrowRight /></Link></div></div></section>

    <section className="border-y-2 border-foreground bg-action-yellow px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl"><SectionTitle index="06" eyebrow="よくある質問" title="参加前の不安に答えます。" /><div className="mt-8 border-t-2 border-foreground">{[
      ["一人でも参加できますか？","はい。多くの学生が一人で参加します。運営メンバーが受付からテーブル移動まで案内します。"],
      ["やりたいことが決まっていなくても大丈夫？","大丈夫です。Table Matchは選考の場ではなく、話しながら興味を見つける場です。"],
      ["服装や参加費は？","普段の服装で参加できます。現在公開中の学生向け企画は参加無料です。"],
      ["申し込んだ情報は企業へ渡りますか？","本人が同意した項目だけを接続支援に使います。連絡先は別途確認なく企業へ渡しません。"],
    ].map(([q,a], index) => <details key={q} className="group border-b-2 border-foreground py-5"><summary className="flex cursor-pointer list-none items-center gap-4 text-lg font-black"><span className="font-mono text-primary">Q{index + 1}</span><span className="flex-1">{q}</span><span className="text-2xl group-open:rotate-45">＋</span></summary><p className="ml-11 mt-4 max-w-3xl leading-8">{a}</p></details>)}</div></div></section>

    <section className="grid border-b-2 border-foreground lg:grid-cols-2"><div className="bg-primary p-8 text-white sm:p-14 lg:p-20"><p className="font-mono text-xs font-black tracking-widest text-action-yellow">学生の方へ</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">話すことから、<br />始めてみる。</h2><Link href="/projects" className="poster-button mt-8 bg-action-yellow text-foreground">参加できる企画を見る<ArrowRight /></Link></div><div className="bg-action-orange p-8 text-white sm:p-14 lg:p-20"><p className="font-mono text-xs font-black tracking-widest text-action-yellow">企業の方へ</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">若者と会社の、<br />接点をつくる。</h2><Link href="/apply/company/company-participation" className="poster-button mt-8 bg-paper text-foreground">出展・協賛を相談する<ArrowRight /></Link></div></section>
  </>
}
