"use client"

import Image from "next/image"
import Link from "next/link"
import { ArrowRight } from "lucide-react"
import { fukuokaMembers, naganoMembers, teamMembers } from "@/components/team"

function MemberGrid({ members, region }: { members: typeof naganoMembers; region: string }) {
  return <section className="mt-14"><div className="flex items-end justify-between border-b-2 border-foreground pb-4"><h2 className="text-4xl font-black sm:text-5xl">{region}支部</h2><span className="font-mono text-sm font-black">{members.length}名</span></div><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{members.map((member) => <article key={member.name} className="border-2 border-foreground bg-white"><div className="relative aspect-[4/5] overflow-hidden border-b-2 border-foreground bg-slate-200"><Image src={member.image} alt={member.name} fill sizes="(max-width: 640px) 50vw, 25vw" className="object-cover grayscale-[10%]" /></div><div className="p-4"><h3 className="text-lg font-black">{member.name}</h3><p className="mt-1 text-xs font-black text-primary">{member.role || "運営メンバー"}</p><p className="mt-3 text-xs leading-6 text-muted-foreground">{member.university}</p></div></article>)}</div></section>
}

export function TeamPoster() {
  const representative = teamMembers[0]
  return <><section className="border-b-2 border-foreground bg-action-yellow px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs font-black tracking-[.22em]">運営メンバー / 長野・福岡</p><h1 className="mt-4 max-w-5xl text-5xl font-black leading-[1.04] sm:text-8xl">この出会いを、<br />学生の手でつくる。</h1><p className="mt-6 max-w-2xl font-bold leading-8">企画、企業への声かけ、広報、当日の進行まで。地域を越えた学生チームが、参加者と同じ目線で場をつくります。</p></div></section><section className="bg-paper px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><div className="grid border-2 border-foreground bg-primary text-white lg:grid-cols-[.78fr_1.22fr]"><div className="relative min-h-[480px] border-b-2 border-foreground lg:border-b-0 lg:border-r-2"><Image src={representative.image ?? "/images/representative.jpg"} alt={`${representative.name} Table Match代表`} fill priority sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover" /></div><div className="p-7 sm:p-12"><p className="font-mono text-xs font-black tracking-widest text-action-yellow">代表</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">{representative.name}</h2><p className="mt-3 font-bold text-white/70">{representative.university}</p><p className="mt-8 text-2xl font-black leading-snug">{representative.bio?.tagline}</p><div className="mt-7 space-y-5 leading-8 text-white/80">{representative.bio?.paragraphs.slice(0,2).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></div><MemberGrid members={naganoMembers} region="長野" /><MemberGrid members={fukuokaMembers} region="福岡" /><div className="mt-16 grid border-2 border-foreground bg-action-orange p-7 text-white sm:grid-cols-[1fr_auto] sm:items-center sm:p-10"><div><p className="font-mono text-xs font-black text-action-yellow">運営へのお問い合わせ</p><h2 className="mt-3 text-3xl font-black">一緒に場をつくる仲間・連携先を募集しています。</h2></div><Link href="mailto:tablematch.info@gmail.com" className="poster-button mt-6 bg-paper text-foreground sm:mt-0">運営へ問い合わせる<ArrowRight /></Link></div></div></section></>
}
